version: '2'

services:
  nice-pool:
    container_name: nice-pool
    build:
      context: ./docker
      dockerfile: Dockerfile.pool
    command:
      - '/bin/bash'
    tty: true

#  nice-redis:
#    container_name: redis-pool
#    image: redis:latest

  nice-monero-mining-node:
    container_name: monero-mining-node
    build:
      context: ./docker
      dockerfile: Dockerfile.monero
    ports:
      - 18082:18082
      - 28080:28080
      - 28081:28081
      - 28082:28082
      - 38081:38081
    volumes:
      - './data/wallet-1:/monero/wallet'
      - './scripts/entrypoint.mining.sh:/entrypoint.sh'
      - './.monero/logs:/monero/logs'
      - './.monero/blockchain/mining:/monero/blockchain'

    command:
      - '/bin/bash'
    tty: true

# ADD NETWORK

