FROM ubuntu:16.04

ARG monero_version=v0.12.0.0

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y wget bzip2

RUN wget -q https://downloads.getmonero.org/cli/monero-linux-x64-${monero_version}.tar.bz2 && \
    tar xf monero-linux-x64-${monero_version}.tar.bz2 && \
    mv monero-${monero_version}/* /usr/bin && \
    rm monero-linux-x64-${monero_version}.tar.bz2 && \
    apt-get autoremove -y

ENTRYPOINT ["/entrypoint.sh"]
